### ISSUE TITLE
The number of arguments for methods dart and objc does not match!

### ISSUE THREAD

**Issue by liqiushui** [dart-native/dart_native#103]
Test ReadMe function Native call Dart:

`    interface.setMethodCallHandler('totalCost',
            (double unitCost, int count, List list) async {
          return {'totalCost: ${unitCost * count}': list};
        });`

swift
`        self.invokeMethod("totalCost", arguments: [0.123456789, 10, ["testArray"]]) { result, err in
            DDLogInfo("invokeMethod totalCost \(result) \(err)")
        }`
always return 'The number of arguments for methods dart and objc does not match!'

**Comment by yulingtianxia** [comment]
try 0.7.5
