### ISSUE TITLE
为了支持多引擎下数据同步，注册多个 block 。在引擎销毁回收出现 crash 

### ISSUE THREAD

**Issue by zeqinjie** [dart-native/dart_native#107]
## 问题
- 为了支持多引擎下数据同步，注册多个 block 用数组存在单利里，当引擎销毁移除 block 会出现 crash 。`removeFromFlutter()`
- 尝试不移除 block 能避免，但在项目会有一定概率出现

## 步骤
- 从 `原生 a` ->  `Flutter a` ->  `原生 b`-> `Flutter b` -> 原生 c`-> `Flutter c`
    -  从 `Next` 按钮点击，原生与 flutter 交替打开
- 当最后回到 `原生 a` 再进 `Flutter a` 出现下面崩溃信息

### 错误信息
<img width="1633" alt="iShot_2022-10-12_11 49 01" src="https://user-images.githubusercontent.com/8444646/195246899-d24612c9-0fb8-498b-b65e-631878e6c7a7.png">

## version
- dart_native: 0.7.5
- flutter:3.0.5
- dart:2.17.6

## 官方 `dart_native` demo 
尝试官方 demo 偶发，概率较低（单引擎）
### 错误信息
![image](https://user-images.githubusercontent.com/8444646/195328618-1c91a71b-69be-4d7c-a1eb-eeb7b454d47e.png)

**Comment by yulingtianxia** [comment]
已修复，发布中。不过 demo 也有一处 crash 需要修复
<img width="805" alt="image" src="https://user-images.githubusercontent.com/433320/195880693-62fca837-e844-4696-b364-50db0bb4b938.png">

**Comment by zeqinjie** [comment]
> 已修复，发布中。不过 demo 也有一处 crash 需要修复 <img alt="image" width="805" src="https://user-images.githubusercontent.com/433320/195880693-62fca837-e844-4696-b364-50db0bb4b938.png">

好像，感谢~

**Comment by zeqinjie** [comment]
@yulingtianxia 大佬。打扰了，发布好像失败

**Comment by yulingtianxia** [comment]
> @yulingtianxia 大佬。打扰了，发布好像失败

@zeqinjie 因为 Xcode 14 打包 xcframework 不支持 armv7 架构，我下载 Xcode 13.2.1 重新打包了一遍，已经发布 0.7.6 版本了
