### ISSUE TITLE
0.7.6版本，flutter工程跑起来会白屏

### ISSUE THREAD

**Issue by percival888** [dart-native/dart_native#108]
升级到0.7.6之后，flutter工程跑起来会白屏，报下面这个错误，恢复到0.7.5就是正常的，why？

![2](https://user-images.githubusercontent.com/19942237/196165612-95e4e3c8-4677-433a-8439-6417ea288418.png)

**Comment by yulingtianxia** [comment]
收到，修复中

**Comment by yulingtianxia** [comment]
@percival888 0.7.7 已发布
