### ISSUE TITLE
ffi版本升级

### ISSUE THREAD

**Issue by LinXunFeng** [dart-native/dart_native#111]
**Describe the bug**
作者可以将 `ffi` 的版本升级到 `2` 以上吗？不然会与 [isar](https://github.com/isar/isar) 的依赖发生冲突

**Comment by yulingtianxia** [comment]
我试试

**Comment by yulingtianxia** [comment]
@LinXunFeng 可以先使用这条分支试试 `feature/flutter3`

**Comment by LinXunFeng** [comment]
好的，辛苦作者

**Comment by LinXunFeng** [comment]
弱弱的问一下，作者计划是什么时候会将升级后的发个版本？

**Comment by yulingtianxia** [comment]
@LinXunFeng 试试 0.7.9

**Comment by LinXunFeng** [comment]
👍
