### ISSUE TITLE
iOS 集成报错 Failed to lookup symbol (dlsym(0x10d77d7e0, RegisterDeallocCallback): symbol not found

### ISSUE THREAD

**Issue by jianniou** [dart-native/dart_native#115]
**Describe the bug**
flutter是 module工程 打包framework 手动集成到Native工程， 但是使用 dart_native中报错
Invalid argument(s): Failed to lookup symbol (dlsym(0x10d77d7e0, RegisterDeallocCallback): symbol not found
想知道是什么问题引起的

平台: iOS
dart_native版本: 0.7.11

**Comment by yulingtianxia** [comment]
> **Describe the bug** flutter是 module工程 打包framework 手动集成到Native工程， 但是使用 dart_native中报错 Invalid argument(s): Failed to lookup symbol (dlsym(0x10d77d7e0, RegisterDeallocCallback): symbol not found 想知道是什么问题引起的
> 
> 平台: iOS dart_native版本: 0.7.11

参考这个 issue：https://github.com/dart-native/dart_native/issues/24
