### ISSUE TITLE
How to call global function

### ISSUE THREAD

**Issue by relf108** [dart-native/dart_native#36]
I've been trying to figure out how to call global functions using your perform method but have been having a lot of trouble. How would I go about doing this?
The method I'm trying to call:
```
 AudioFileOpenURL (
    CFURLRef inFileRef, 
    AudioFilePermissions inPermissions,
    AudioFileTypeID inFileTypeHint,
    AudioFileID	__nullable * __nonnull	outAudioFile
)
```
Thanks in advance!

**Comment by yulingtianxia** [comment]
@relf108  DartNative doesn't support C function for now. Cuz you can use `dart:ffi` directly.

**Comment by relf108** [comment]
That clears things up. Thanks for the quick response.
