### ISSUE TITLE
我该如何返回一个byte[]

### ISSUE THREAD

**Issue by yiszza** [dart-native/dart_native#41]
public byte[] getData() {
   byte[] result = new byte[]{0,1,2,3,4,5,6,7,8,9};
    return result;
  }

**Comment by yulingtianxia** [comment]
@yiszza 问下是 Java 里的 byte 么？

**Comment by yiszza** [comment]
> 

您好 , 是java的byte数组

**Comment by hui19** [comment]
数组、集合还没支持，预计本周支持哈

**Comment by hui19** [comment]
数组目前还没支持到，预计本周可以支持

**Comment by yiszza** [comment]
> 

好的 , 谢谢
