### ISSUE TITLE
x86虚拟机运行调用异步消息报错

### ISSUE THREAD

**Issue by wuguangyong** [dart-native/dart_native#81]
D/CallbackHandler(32439): invoke method: callbackComplex
E/_native_exampl(32439): JNI ERROR (app bug): accessed stale Local 0xc9  (index 12 in a table of size 11)
F/_native_exampl(32439): java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0xc9
F/_native_exampl(32439): java_vm_ext.cc:577]     from java.lang.Object com.dartnative.dart_native.CallbackInvocationHandler.hookCallback(long, java.lang.String, int, java.lang.String[], java.lang.Object[], java.lang.String)
F/_native_exampl(32439): runtime.cc:655] Runtime aborting...
F/_native_exampl(32439): runtime.cc:655] Dumping all threads without mutator lock held
F/_native_exampl(32439): runtime.cc:655] All threads:
F/_native_exampl(32439): runtime.cc:655] DALVIK THREADS (19):
F/_native_exampl(32439): runtime.cc:655] "main" prio=10 tid=1 Runnable

**Comment by hui19** [comment]
重复deleteLocalRef，在x86下会报错，修复可查看这个[PR](https://github.com/dart-native/dart_native/pull/83) @wuguangyong
