### ISSUE TITLE
有没有原生调dart的例子？

### ISSUE THREAD

**Issue by ruiq** [dart-native/dart_native#84]
不知道是不是我没找到，好像没看到原生调dart的例子？

**Comment by yulingtianxia** [comment]
@ruiq 有的，是需要通过 dart 先传入一个 Java/OC 对象给 native，然后 native 用这个对象可以回调到 dart 的 function。支持 Dart Function 自动转成 OC Block，Java Lambda 表达式也马上要支持了。

**Comment by ruiq** [comment]
> yulingtianxia

请问是在哪里有这个例子？我确实没有翻到。。。

**Comment by yulingtianxia** [comment]
OC 的 Block 例子：
https://github.com/dart-native/dart_native/blob/dc99cfd6f8cbff47763f9fc98b3710fba4edc13f/dart_native/example/lib/ios/runtimestub.dart#L220

OC 的 Delegate 例子：
https://github.com/dart-native/dart_native/blob/dc99cfd6f8cbff47763f9fc98b3710fba4edc13f/dart_native/example/lib/ios/runtimestub.dart#L240 

Swift 的 Function 例子：
https://github.com/dart-native/dart_native/blob/dc99cfd6f8cbff47763f9fc98b3710fba4edc13f/dart_native/example/lib/ios/swiftstub.dart#L37

Java 的 Listener 例子：
https://github.com/dart-native/dart_native/blob/dc99cfd6f8cbff47763f9fc98b3710fba4edc13f/dart_native/example/lib/android/runtimestub.dart#L96

**Comment by ruiq** [comment]
抱歉才回复
我试了一下，回调方法是不是不能带参？
不带参数的话，native->flutter可以走通
带参数的话，比如(String foo) { debugPrint(foo); }
类似这样的闭包传不过去，会报错
Native callback to Dart failed! Invalid port or isolate died

**Comment by yulingtianxia** [comment]
> 抱歉才回复
> 
> 我试了一下，回调方法是不是不能带参？
> 
> 不带参数的话，native->flutter可以走通
> 
> 带参数的话，比如(String foo) { debugPrint(foo); }
> 
> 类似这样的闭包传不过去，会报错
> 
> Native callback to Dart failed! Invalid port or isolate died

带参数是支持的，例子里有的。可以搜block或delegate，有带参数和不带参数的例子

**Comment by ruiq** [comment]
> 

找到原因了，block里用的string参数需要指定成NSString类型。。。然后用foo.raw来获取

**Comment by yulingtianxia** [comment]
> > 
> 
> 
> 
> 找到原因了，block里用的string参数需要指定成NSString类型。。。然后用foo.raw来获取

嗯这里的确有优化的空间，可以加个策略自动转换下。其实codegen可以自动生成这些dart代码，这样就不容易写错了
