### ISSUE TITLE
dart调用安卓原生方法失败

### ISSUE THREAD

**Issue by LiuDongCai** [dart-native/dart_native#86]
你好，我们flutter module和原生是同一级目录依赖的，然后flutter需要调用原生的方法
dart代码
`@native(javaClass : "com/addcn/android/flutterservice/TWInfoService")
class AndroidAppInfoService extends JObject｛
...
｝`
`@nativeRoot
@pragma('vm:entry-point')
void main() {
  DartNative.init();
  runTw591FlutterModules();//类型example的runDartNativeExample()方法
  runApp(const MyApp());
}`
可是当调用AndroidAppInfoService的时候闪退，请问是因为项目在同一级导致的路径不对吗？请问要怎么改呢

**Comment by LiuDongCai** [comment]
com/addcn/android/flutterservice/TWInfoService  路径是这个 刚刚复制错了，请问有错吗

**Comment by hui19** [comment]
@LiuDongCai 有crash堆栈方便发一下吗

**Comment by LiuDongCai** [comment]
> @LiuDongCai 有crash堆栈方便发一下吗

Java class name is null, you can specify the java class name in constructor or use @nativeJavaClass annotation to specify the java class

**Comment by LiuDongCai** [comment]
> @LiuDongCai 有crash堆栈方便发一下吗

![image](https://user-images.githubusercontent.com/18276939/146854712-892b8317-fbee-4e2f-90a0-5f31a3e1f9c5.png)
这几个我没有写，是一定要的嘛，是要写在BaseApplication还是BaseActivity呢

**Comment by yulingtianxia** [comment]
> > @LiuDongCai 有crash堆栈方便发一下吗
> 
> Java class name is null, you can specify the java class name in constructor or use @nativeJavaClass annotation to specify the java class

@hui19 看起来注释和异常里对 Annotation 的描述需要更新下了

**Comment by yulingtianxia** [comment]
@LiuDongCai 加上去已经 OK 了么

**Comment by LiuDongCai** [comment]
> @LiuDongCai 加上去已经 OK 了么

Ok了
