### ISSUE TITLE
某些字符串从iOS返回dart会报错

### ISSUE THREAD

**Issue by ruiq** [dart-native/dart_native#92]
Flutter version 2.10.4
dart_native: ^0.6.3

发现在iOS下（安卓不会），返回某些字符串会报错，比如"鎮"，我把example里的示例改动了一下：
- (NSString *)fooNSString:(NSString *)str {
//    DDLogInfo(@"%s arg: %@", __FUNCTION__, str);
    return @"鎮";
}

发现报错了，真机模拟器都如此。

**Comment by yulingtianxia** [comment]
@ruiq 请更新到 0.6.6 版本
