### ISSUE TITLE
安卓系统某些字符串在flutter获取是乱码

### ISSUE THREAD

**Issue by ruiq** [dart-native/dart_native#97]
[✓] Flutter (Channel flutter-2.8-candidate.16, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale
    zh-Hans-CN)
Android SDK version 31.0.0
在安卓系统下，获取这个字符串，会返回乱码，请帮忙排查一下。
可以用自带的example项目unit_test.dart里getStringAsync处输入该字符串复现。

'[{"id":16,"regionid":1,"sectionid":"1","name":"台北車站生活圈","lat":"25.0440392","lng":"121.5139124"},{"id":17,"regionid":1,"sectionid":"1","name":"善導寺站生活圈","lat":"25.0432715","lng":"121.5247305"},{"id":22,"regionid":1,"sectionid":"1,5","name":"東門生活圈","lat":"25.0350275","lng":"121.5257406"},{"id":23,"regionid":1,"sectionid":"1","name":"植物園生活圈","lat":"25.0316631","lng":"121.5090781"},{"id":24,"regionid":1,"sectionid":"1","name":"古亭生活圈","lat":"25.0258859","lng":"121.5184339"},{"id":26,"regionid":1,"sectionid":"1,5","name":"公館生活圈","lat":"25.0155842","lng":"121.5298605"}]'

**Comment by ruiq** [comment]
在最新版本DN依旧复现

**Comment by hui19** [comment]
#98 uint16指针释放时机有问题，长字符释放后内存被重写，导致了读取乱码

**Comment by yulingtianxia** [comment]
0.7.3 版本已修复
