### ISSUE TITLE
type 'Bool' not found

### ISSUE THREAD

**Issue by yilugesanghua** [dart-native/dart_native#99]
**Describe the bug**
../../.pub-cache/hosted/pub.flutter-io.cn/dart_native-0.7.3/lib/src/darwin/runtime/internal/native_runtime.dart:24:5: Error: Type 'Bool' not found.
    Bool returnString,
    ^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/dart_native-0.7.3/lib/src/darwin/runtime/internal/native_runtime.dart:110:5: Error: Type 'Bool' not found.
    Bool shouldReturnAsync,
    ^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/dart_native-0.7.3/lib/src/android/runtime/functions.dart:75:21: Error: 'Bool' isn't a type.
                    Bool isInterface)>>('InvokeNativeMethod')
                    ^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/dart_native-0.7.3/lib/src/android/runtime/functions.dart:76:10: Error: Expected type 'NativeFunction<Pointer<Void> Function(Pointer<Void>, Pointer<Utf8>, Pointer<Pointer<Void>>, Pointer<Pointer<Utf8>>, Int32, Pointer<Utf8>, Uint32, Pointer<NativeFunction<Void Function(Pointer<Void>, Pointer<Utf8>, Pointer<Pointer<Utf8>>, Int32)>>, Int64, Int32, invalid-type)>' to be a valid and instantiated subtype of 'NativeType'.
 - 'NativeFunction' is from 'dart:ffi'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Void' is from 'dart:ffi'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' ('../../.pub-cache/hosted/pub.flutter-io.cn/ffi-1.2.1/lib/src/utf8.dart').
 - 'Int32' is from 'dart:ffi'.
 - 'Uint32' is from 'dart:ffi'.
 - 'Int64' is from 'dart:ffi'.
        .asFunction();
         ^
../../.pub-cache/hosted/pub.flutter-io.cn/dart_native-0.7.3/lib/src/darwin/runtime/internal/native_runtime.dart:35:17: Error: Expected type 'NativeFunction<Int32 Function(Pointer<Void>, Pointer<Void>, Pointer<Utf8>, invalid-type, Pointer<NativeFunction<Void Function(Pointer<Pointer<Pointer<Void>>>, Pointer<Pointer<Void>>, Int32, Pointer<Pointer<Utf8>>, Int32)>>, Int64)>' to be a valid and instantiated subtype of 'NativeType'.
 - 'NativeFunction' is from 'dart:ffi'.
 - 'Int32' is from 'dart:ffi'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Void' is from 'dart:ffi'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' ('../../.pub-cache/hosted/pub.flutter-io.cn/ffi-1.2.1/lib/src/utf8.dart').
 - 'Int64' is from 'dart:ffi'.
    nativeDylib.lookupFunction<AddMethodC, AddMethodD>('native_add_method');
                ^
../../.pub-cache/hosted/pub.flutter-io.cn/dart_native-0.7.3/lib/src/darwin/runtime/internal/native_runtime.dart:118:6: Error: Expected type 'NativeFunction<Pointer<Void> Function(Pointer<Utf8>, Pointer<NativeFunction<Void Function(Pointer<Pointer<Pointer<Void>>>, Pointer<Pointer<Void>>, Int32, Int32, Int64)>>, invalid-type, Int64)>' to be a valid and instantiated subtype of 'NativeType'.
 - 'NativeFunction' is from 'dart:ffi'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Void' is from 'dart:ffi'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' ('../../.pub-cache/hosted/pub.flutter-io.cn/ffi-1.2.1/lib/src/utf8.dart').
 - 'Int32' is from 'dart:ffi'.
 - 'Int64' is from 'dart:ffi'.
    .lookupFunction<BlockCreateC, BlockCreateD>('native_block_create');
     ^

**To Reproduce**
1. dart_native: 0.7.3
2. flutter:2.5.3
3. dart:2.14.4

**Comment by yulingtianxia** [comment]
Try `flutter pub get`

**Comment by yilugesanghua** [comment]
I try it. 
Running "flutter pub get" in jdf_jddoctor_cross_platform_module...      1,507ms
but it still got   'type 'Bool' not found'

**Comment by yulingtianxia** [comment]
Try dart 2.15

**Comment by yulingtianxia** [comment]
@yilugesanghua Try 0.7.4

**Comment by yilugesanghua** [comment]
it‘s ok now
